### ISSUE TITLE
Satzende ändern

### ISSUE THREAD

**Issue by simonszu** [MoriPastaPizza/GermanToOgreTranslator#3]
Der Bot lässt viele Sätze mit "des Bast scho" enden. Eventuell kann man das mal sporadisch ändern auf "dadzächlich sogar" oder "des bast scho hätt ich gsacht".

Genau so könnte er ein paar mehr Sätze gerne mit Etzala beginnen...

**Comment by MoriPastaPizza** [comment]
Das mit dem Satzende ist/war ein Problem mit dem Zufallssystem, bisher hat es immer ein Zufälliges Wort für einen Post ausgewählt, weshalb die gleichen Wörter immer gleich ersetzt wurden.
Mit dem nächsten Update wird für jedes Wort (also auch Satzende) ein neues ausgewählt. Damit sollte sich das Problem lösen.

Das mit dem dem Satzanfang ist eine super Idee und werde ich so übernehmen. Möchtest du denn in einem Header verewigt werden? Wenn ja wie?

**Comment by simonszu** [comment]
Ne, lass mal. Ich bin eher passiver Partizipator im Game.

**Comment by MoriPastaPizza** [comment]
Kannst ja auch nur irgendein dummes Zitat oder sowas nehmen ;)
